// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolutionDesigner.Models;

namespace SolutionDesigner.Migrations
{
    [DbContext(typeof(SolutionDesignerContext))]
    [Migration("20181029162101_SupportCacadeDelete")]
    partial class SupportCacadeDelete
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SolutionDesigner.Models.Column", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DashboardItemId");

                    b.Property<string>("name");

                    b.Property<int>("offset");

                    b.Property<int>("type");

                    b.HasKey("id");

                    b.HasIndex("DashboardItemId");

                    b.ToTable("Column");
                });

            modelBuilder.Entity("SolutionDesigner.Models.DashboardItem", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cols");

                    b.Property<string>("itemType");

                    b.Property<int>("rows");

                    b.Property<string>("serializedChartOptions");

                    b.Property<int>("x");

                    b.Property<int>("y");

                    b.HasKey("Id");

                    b.ToTable("DashboardItem");
                });

            modelBuilder.Entity("SolutionDesigner.Models.Query", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DashboardItemId");

                    b.Property<string>("guiItemName");

                    b.Property<string>("query");

                    b.HasKey("id");

                    b.HasIndex("DashboardItemId");

                    b.ToTable("Query");
                });

            modelBuilder.Entity("SolutionDesigner.Models.Column", b =>
                {
                    b.HasOne("SolutionDesigner.Models.DashboardItem", "DashboardItem")
                        .WithMany("columns")
                        .HasForeignKey("DashboardItemId");
                });

            modelBuilder.Entity("SolutionDesigner.Models.Query", b =>
                {
                    b.HasOne("SolutionDesigner.Models.DashboardItem", "DashboardItem")
                        .WithMany("queries")
                        .HasForeignKey("DashboardItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
