// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolutionDesigner.Models;

namespace SolutionDesigner.Migrations
{
    [DbContext(typeof(SolutionDesignerContext))]
    [Migration("20181101200508_add-image-storer")]
    partial class addimagestorer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SolutionDesigner.Models.Column", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChartDashboardItemId");

                    b.Property<string>("name");

                    b.Property<int>("offset");

                    b.Property<int>("type");

                    b.HasKey("id");

                    b.HasIndex("ChartDashboardItemId");

                    b.ToTable("Column");
                });

            modelBuilder.Entity("SolutionDesigner.Models.DashboardItem", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("cols");

                    b.Property<string>("itemGroup");

                    b.Property<string>("itemType");

                    b.Property<int>("rows");

                    b.Property<int>("x");

                    b.Property<int>("y");

                    b.HasKey("Id");

                    b.ToTable("DashboardItem");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DashboardItem");
                });

            modelBuilder.Entity("SolutionDesigner.Models.Image", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentDisposition");

                    b.Property<string>("ContentType");

                    b.Property<string>("FileName");

                    b.Property<long>("Length");

                    b.Property<string>("Name");

                    b.Property<byte[]>("imageBin");

                    b.HasKey("id");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("SolutionDesigner.Models.Query", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DashboardItemId");

                    b.Property<string>("guiItemName");

                    b.Property<string>("query");

                    b.HasKey("id");

                    b.HasIndex("DashboardItemId");

                    b.ToTable("Query");
                });

            modelBuilder.Entity("SolutionDesigner.Models.TextElement", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Color");

                    b.Property<int>("DashboarItemdRef");

                    b.Property<string>("Fontfamily");

                    b.Property<double>("Size");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("TextElement");
                });

            modelBuilder.Entity("SolutionDesigner.Models.AppDashboardItem", b =>
                {
                    b.HasBaseType("SolutionDesigner.Models.DashboardItem");


                    b.ToTable("AppDashboardItem");

                    b.HasDiscriminator().HasValue("AppDashboardItem");
                });

            modelBuilder.Entity("SolutionDesigner.Models.ChartDashboardItem", b =>
                {
                    b.HasBaseType("SolutionDesigner.Models.DashboardItem");

                    b.Property<string>("serializedChartOptions");

                    b.ToTable("ChartDashboardItem");

                    b.HasDiscriminator().HasValue("ChartDashboardItem");
                });

            modelBuilder.Entity("SolutionDesigner.Models.TextDashoardItem", b =>
                {
                    b.HasBaseType("SolutionDesigner.Models.DashboardItem");


                    b.ToTable("TextDashoardItem");

                    b.HasDiscriminator().HasValue("TextDashoardItem");
                });

            modelBuilder.Entity("SolutionDesigner.Models.Column", b =>
                {
                    b.HasOne("SolutionDesigner.Models.ChartDashboardItem", "ChartDashboardItem")
                        .WithMany("columns")
                        .HasForeignKey("ChartDashboardItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SolutionDesigner.Models.Query", b =>
                {
                    b.HasOne("SolutionDesigner.Models.DashboardItem", "DashboardItem")
                        .WithMany("queries")
                        .HasForeignKey("DashboardItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SolutionDesigner.Models.TextElement", b =>
                {
                    b.HasOne("SolutionDesigner.Models.TextDashoardItem", "TextDashboardItem")
                        .WithOne("TextOptions")
                        .HasForeignKey("SolutionDesigner.Models.TextElement", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
